### ISSUE TITLE
cannot clone it

### ISSUE THREAD

**Issue by sasagr** [derlin/investing-historical-data#1]
I m getting this error while trying to clone it

Salvatores-MacBook-Pro:~ salvatoregrado$ git clone git@github.com:derlin/investing-historical-data.git
Cloning into 'investing-historical-data'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Shall I do something different?
I also tried with sudo but same thing

**Comment by derlin** [comment]
Dear sagagr, 

I don't think the problem comes from the repository.  Could you check the [Github Help: permission denied (public key)](https://help.github.com/articles/error-permission-denied-publickey/) faq ? In case it still gives you error, try to clone the repository using https and let me know if it is better.

**Comment by sasagr** [comment]
I managed to clone it using Github Desktop for Mac and I managed to make it working as you ca see it:

```
$ node investing.js get -i 8861 -s 01/01/2018 -e 01/21/2018
Date, Price, Open, High, Low, Vol., Change %

Jan 19, 2018, 608.00, 611.25, 613.50, 605.25, 68.18K, -0.61%
Jan 18, 2018, 611.75, 613.50, 613.75, 607.25, 95.08K, 0.00%
Jan 17, 2018, 611.75, 614.75, 615.00, 607.00, 101.88K, -0.49%
Jan 16, 2018, 614.75, 619.25, 621.00, 610.50, 74.31K, -0.65%
Jan 15, 2018, 618.75, 618.75, 622.75, 614.50, 60.79K, 0.98%
Jan 12, 2018, 612.75, 614.75, 617.50, 609.50, 55.36K, 0.12%
Jan 11, 2018, 612.00, 612.75, 616.75, 612.00, 8.26K, 0.00%
Jan 10, 2018, 612.00, 611.00, 615.75, 609.00, 48.11K, 1.12%
Jan 09, 2018, 605.25, 604.00, 612.75, 600.75, 41.13K, 0.71%
Jan 08, 2018, 601.00, 607.50, 607.75, 600.50, 41.23K, -0.50%
Jan 05, 2018, 604.00, 615.25, 618.50, 601.75, 39.88K, -0.66%
Jan 04, 2018, 608.00, 610.00, 620.00, 605.75, 37.12K, 0.21%
Jan 03, 2018, 606.75, 598.50, 611.75, 596.25, 56.48K, 1.63%
Jan 02, 2018, 597.00, 603.50, 606.75, 596.25, 34.78K, -0.54%
```

I also tried to extract the data for a future index Dow Jones 30 Futures - Mar 18 where the id should be 8873 (I got this from the source page: https://www.investing.com/quotes/8873)
but I get 
>commodity 8873 does not exist.

Does the program only extract commodities? and not other stuff like Indices?

**Comment by derlin** [comment]
As the name of the project suggests, it is only possible to fetch data from the past (historical data), not future indices. But you can open a feature request and I can see into it as soon as I have some time 😄 .

Now, you can still get past information on the _Dow Jones 30 Futures_. Or at least you _should_. The error you get

> commodity XXX does not exist

has been fixed in the development branch (see branch `economic-calendar`, latest commit being 1452e75). 

--------------

The development version changed a bit, so here is an example usage _for past data_:

```
npm start -- history search "Dow Jones 30" -c Indices

8873, Dow Jones 30 Futures, indicefuture, USA, https://www.investing.com/indices/us-30-futures
954711, Dow Jones Italy Titans 30 EUR, indice, Italy, https://www.investing.com/indices/dj-italy-titans-30-eur
...
```

```
npm start -- history get 8873         

Date, Price, Open, High, Low, Vol., Change %
Jan 19, 2018, 26,046.0, 25,944.0, 26,086.0, 25,876.0, -, 0.40%
Jan 18, 2018, 25,941.0, 26,084.0, 26,149.0, 25,912.0, 190.65K, -0.60%
Jan 17, 2018, 26,098.0, 25,828.0, 26,120.0, 25,775.0, 188.03K, 1.08%
Jan 16, 2018, 25,819.0, 25,813.0, 26,061.0, 25,682.0, 309.93K, -0.50%
Jan 15, 2018, 25,948.0, 25,896.0, 25,985.0, 25,868.0, -, 0.20%
Jan 14, 2018, 25,896.0, 25,813.0, 25,900.0, 25,811.0, -, 0.37%
...
```

**Comment by sasagr** [comment]
COMPLETELY REDIT.
Sorry for any troubles. Eventually we will edit this post as we see fit.
My previous error was coming because I forgot to npm install since I was re-adding the repo from zero.
Now I do not have that error anymore but I get the following:

Salvatores-MacBook-Pro:investing-historical-data salvatoregrado$ npm start -- history get 8873

> investing-historical-data@1.0.0 start /Users/salvatoregrado/Documents/GitHub/investing-historical-data
> node investing.js "history" "get" "8873"

Salvatores-MacBook-Pro:investing-historical-data salvatoregrado$ npm start -- history search "Dow Jones 30" -c Indices

> investing-historical-data@1.0.0 start /Users/salvatoregrado/Documents/GitHub/investing-historical-data
> node investing.js "history" "search" "Dow Jones 30" "-c" "Indices"

Salvatores-MacBook-Pro:investing-historical-data salvatoregrado$

Also now I can get the history for the 8873
Salvatores-MacBook-Pro:investing-historical-data salvatoregrado$ node investing.js get -i 8873 -s 01/01/2018 -e 01/21/2018
Date, Price, Open, High, Low, Vol., Change %

Jan 19, 2018, 26,046.0, 25,944.0, 26,086.0, 25,876.0, -, 0.40%
Jan 18, 2018, 25,941.0, 26,084.0, 26,149.0, 25,912.0, 190.65K, -0.60%
Jan 17, 2018, 26,098.0, 25,828.0, 26,120.0, 25,775.0, 188.03K, 1.08%
Jan 16, 2018, 25,819.0, 25,813.0, 26,061.0, 25,682.0, 309.93K, -0.50%
Jan 15, 2018, 25,948.0, 25,896.0, 25,985.0, 25,868.0, -, 0.20%
Jan 14, 2018, 25,896.0, 25,813.0, 25,900.0, 25,811.0, -, 0.37%
Jan 12, 2018, 25,801.0, 25,539.0, 25,813.0, 25,531.0, 152.58K, 0.96%
Jan 11, 2018, 25,555.0, 25,351.0, 25,561.0, 25,330.0, 115.64K, 0.80%
Jan 10, 2018, 25,351.0, 25,354.0, 25,384.0, 25,222.0, 143.64K, -0.09%
Jan 09, 2018, 25,373.0, 25,246.0, 25,415.0, 25,238.0, 125.14K, 0.49%
Jan 08, 2018, 25,250.0, 25,272.0, 25,359.0, 25,210.0, 108.70K, -0.08%
Jan 05, 2018, 25,269.0, 25,067.0, 25,282.0, 25,059.0, 106.86K, 0.86%
Jan 04, 2018, 25,053.0, 24,884.0, 25,082.0, 24,878.0, 115.66K, 0.70%
Jan 03, 2018, 24,878.0, 24,796.0, 24,908.0, 24,768.0, 93.40K, 0.44%
Jan 02, 2018, 24,768.0, 24,735.0, 24,857.0, 24,716.0, 105.42K, -0.03%
Jan 01, 2018, 24,775.0, 24,735.0, 24,779.0, 24,726.0, -, 0.16%
Salvatores-MacBook-Pro:investing-historical-data salvatoregrado$ 

and I was not expecting it.
But still with the empty row and now that figures have commas, you can imagine what happens into the excel file :)

Am I missing something, maybe I m not correctly using the commands to access the dev branch?

**Comment by sasagr** [comment]
OK. I cloned and installed the dev branch and I can make it working s per your above examples.
The only I have now it is the format of the prices that have the "," that messes up the cvs import

**Comment by derlin** [comment]
Yep I know that 😅  see issue #3 . I just pushed a dirty fix, it should be ok for your case.
