### ISSUE TITLE
output not correctly formatted

### ISSUE THREAD

**Issue by sasagr** [derlin/investing-historical-data#2]
I see the output comes out as:
Date, Price, Open, High, Low, Vol., Change %
Jan 19, 2018, 608.00, 611.25, 613.50, 605.25, 68.18K, -0.61%

When imported in excel as csv, it will be formatted wrongly as:
Date-> Jan 19
Price -> 2018
Open -> 608.00
....

This probably happens because of the way the date is originally formatted. Probably it could be better to format it as MM/DD/YEAR and not as Month D, Year

Also could it possible to remove the blank row between data description and data as it shows in the excel imported cvs file?

Date | Price | Open | High | Low | Vol. | Change   % |  
(empty row)
Jan-19 | 2018 | 608 | 611.25 | 613.5 | 605.25 | 68.18K | -0.61%

**Comment by derlin** [comment]
First, thank you for your valuable inputs.

The empty row has been removed in the development version. 

Concerning the date, it was also one of my concerns: I agree that an ISO format would be better. BUTdealing with dates is always a pain in the ***, especially in investing.com where date format varies across pages... I will thus mark this issue as enhancement. Maybe for a future release ?

**Comment by sasagr** [comment]
thanks! The date is really messed up. Not only because of the comma after the the day (Dec 29, 2017) but also because the cell containing Dec 29 is seen as 12/01/2029 and this makes the information unusable as it is.
Hope you can add even a quick dirty fix for it while working on a proper one

**Comment by sasagr** [comment]
Otherwise pls let me know how do you deal with the DATE with your .csv output files because I have no idea on how to handle them. 
Thanks

**Comment by derlin** [comment]
I pushed a new quick fix. I haven't tested it thoroughly and implemented it only for `history get`, but it seems to be ok. Please let me know if you discover a bug.

Note: the format of the date is `DD/MM/YYYY` (sorry, but I can't stand the american format with months first 😸 )

**Comment by sasagr** [comment]
It seems to be working great, no bug so far! I agree with you about american format
